/**
 * @file demo_device.c
 * @brief Concrete implementation of the "demo" driver class.
 *
 * This driver has no real hardware behind it. Every API call (enable,
 * disable, get_status) is answered with a log message so you can
 * observe the entire call chain: application → API header → ops table
 * → this file.
 *
 * One device instance is created automatically for every DT node with
 * @code
 *   compatible = "demo-device";
 *   status = "okay";
 * @endcode
 *
 * @copyright Copyright (c) 2024 Nordic Semiconductor ASA
 * @license   Apache-2.0
 */

/** @cond Tells Zephyr DT macros which compatible string this driver handles (snake_case of "demo-device"). */
#define DT_DRV_COMPAT demo_device
/** @endcond */

#include <zephyr/device.h>
#include <zephyr/devicetree.h>
#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>

#include <app/drivers/demo.h>

LOG_MODULE_REGISTER(demo_device, CONFIG_DEMO_LOG_LEVEL);

/**
 * @brief Per-instance runtime state.
 *
 * Allocated once per device by the kernel; mutated by the API functions.
 */
struct demo_device_data {
	bool enabled; /**< @brief Current enable/disable state. */
};

/**
 * @brief Per-instance compile-time configuration, populated from the DTS.
 *
 * Fields are set once at initialisation and never changed afterwards.
 */
struct demo_device_config {
	const char *label; /**< @brief Human-readable label from the DTS @c label property; may be @c NULL. */
    int numeric_id; /**< @brief Optional numeric ID from the DTS @c numeric_id property; may be -1 if not set. */
};

/**
 * @brief Resolve a human-readable name for log messages.
 *
 * Returns the DTS @c label string if present, otherwise falls back to
 * the kernel device name.
 *
 * @param dev  Device instance.
 * @return     Null-terminated string suitable for use in log messages.
 */
static const char *dev_label(const struct device *dev)
{
	const struct demo_device_config *cfg = dev->config;

	return (cfg->label != NULL) ? cfg->label : dev->name;
}

/**
 * @defgroup demo_device_impl Demo device driver — internal implementation
 * @{
 */

/**
 * @brief Enable the demo device.
 *
 * Implements @ref demo_driver_api::enable. Logs the call and transitions
 * the device state to ENABLED. Returns @c -EALREADY if already enabled.
 *
 * @param dev  Device instance.
 * @retval 0        Success.
 * @retval -EALREADY Device was already enabled.
 */
static int demo_device_enable(const struct device *dev)
{
	struct demo_device_data *data = dev->data;

	LOG_INF("[%s] demo_enable() called", dev_label(dev));

	if (data->enabled) {
		LOG_WRN("[%s] already enabled — returning -EALREADY",
			dev_label(dev));
		return -EALREADY;
	}

	data->enabled = true;
	LOG_INF("[%s] device is now ENABLED", dev_label(dev));
	return 0;
}

/**
 * @brief Disable the demo device.
 *
 * Implements @ref demo_driver_api::disable. Logs the call and transitions
 * the device state to DISABLED. Returns @c -EALREADY if already disabled.
 *
 * @param dev  Device instance.
 * @retval 0        Success.
 * @retval -EALREADY Device was already disabled.
 */
static int demo_device_disable(const struct device *dev)
{
	struct demo_device_data *data = dev->data;

	LOG_INF("[%s] demo_disable() called", dev_label(dev));

	if (!data->enabled) {
		LOG_WRN("[%s] already disabled — returning -EALREADY",
			dev_label(dev));
		return -EALREADY;
	}

	data->enabled = false;
	LOG_INF("[%s] device is now DISABLED", dev_label(dev));
	return 0;
}

/**
 * @brief Read the current status of the demo device.
 *
 * Implements @ref demo_driver_api::get_status. Logs the call and writes
 * the current @ref demo_status value into @p status.
 *
 * @param dev     Device instance.
 * @param status  Output pointer; set to @ref DEMO_STATUS_ENABLED or
 *                @ref DEMO_STATUS_DISABLED.
 * @retval 0  Always succeeds.
 */
static int demo_device_get_status(const struct device *dev,
				  enum demo_status *status)
{
	const struct demo_device_data *data = dev->data;

	LOG_INF("[%s] demo_get_status() called", dev_label(dev));

	*status = data->enabled ? DEMO_STATUS_ENABLED : DEMO_STATUS_DISABLED;

	LOG_INF("[%s] status = %s", dev_label(dev),
		*status == DEMO_STATUS_ENABLED ? "ENABLED" : "DISABLED");

	return 0;
}

/** @} */ /* end demo_device_impl */

/**
 * @brief Driver class operations table.
 *
 * Wires the concrete functions above into the @ref demo_driver_api vtable.
 * Zephyr uses this struct to dispatch calls from @ref demo_enable(),
 * @ref demo_disable(), and @ref demo_get_status().
 */
static DEVICE_API(demo, demo_device_api) = {
	.enable     = demo_device_enable,
	.disable    = demo_device_disable,
	.get_status = demo_device_get_status,
};

/**
 * @brief Initialise a demo device instance.
 *
 * Called by the kernel during the POST_KERNEL init phase, once per device
 * instance generated by @ref DEMO_DEVICE_DEFINE. Sets the device to the
 * DISABLED state and emits an informational log message.
 *
 * @param dev  Device instance being initialised.
 * @retval 0   Always succeeds.
 */
static int demo_device_init(const struct device *dev)
{
	const struct demo_device_config *cfg = dev->config;
	struct demo_device_data *data = dev->data;

	data->enabled = false; /**< Start in the DISABLED state. */

	LOG_INF("[%s] demo_device initialised (label=%s)",
		dev->name,
		cfg->label != NULL ? cfg->label : "<none>");

	return 0;
}

/**
 * @brief Instantiation macro — expands once per enabled DT node.
 *
 * @ref DT_INST_FOREACH_STATUS_OKAY invokes this macro for every DT node
 * that has @c compatible = "demo-device" and @c status = "okay".
 *
 * For each instance @p inst it creates:
 *   - @c demo_data_##inst   — runtime state struct (@ref demo_device_data)
 *   - @c demo_config_##inst — compile-time config (@ref demo_device_config)
 *   - A @c struct @c device registered with the Zephyr device model
 *
 * @param inst  Zero-based instance index assigned by the DT compiler.
 */
#define DEMO_DEVICE_DEFINE(inst)                                               \
	static struct demo_device_data demo_data_##inst;                       \
                                                                               \
	static const struct demo_device_config demo_config_##inst = {          \
		.label = DT_INST_PROP_OR(inst, label, NULL),                   \
        .numeric_id = DT_INST_PROP_OR(inst, numeric_id, -1),           \
	};                                                                     \
                                                                               \
	DEVICE_DT_INST_DEFINE(inst,                                            \
			      demo_device_init,                                \
			      NULL,           /**< No power management callback. */ \
			      &demo_data_##inst,                               \
			      &demo_config_##inst,                             \
			      POST_KERNEL,                                     \
			      CONFIG_DEMO_INIT_PRIORITY,                       \
			      &demo_device_api);

DT_INST_FOREACH_STATUS_OKAY(DEMO_DEVICE_DEFINE)
